language: node_js # don't install any environment
node_js:
  - lts/*

install:
  - yarn install

script:
  - yarn docs:build

branches:
  only:
  - master

before_deploy:
  - openssl aes-256-cbc -K $encrypted_76cafa646b8f_key -iv $encrypted_76cafa646b8f_iv -in nk-docu-deploykey.enc -out nk-docu-deploykey -d

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: .vuepress/dist
  deploy_key: deploy_key
  keep_history: true
  edge:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
